In [2]:
import sys
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
#mport utilities.localtests as localtests
from mpl_toolkits.mplot3d import axes3d
from tqdm import tqdm

In [91]:
x = np.random.randn(2, 2)
y = np.random.randn(3, 2)
display(x)
display(y)

array([[ 0.34328959,  0.78642789],
       [-1.18037682,  1.73347216]])

array([[-0.79015968, -0.5179102 ],
       [-1.16374802, -0.96441859],
       [ 1.02117727,  0.94736293]])

In [33]:
y = y.T
display(x)
display(y)

array([[-1.12327394,  0.71550579],
       [-1.36914876,  1.03560648]])

array([[ 0.48808644, -0.50618654,  1.53170346],
       [ 1.86404905,  0.51010584,  0.11357254]])

In [34]:
N = x.shape[0]
M = y.shape[0]
N, M

(2, 2)

In [96]:
x_expanded = x[:, np.newaxis, :]
y_expanded = y[np.newaxis, :, :]
squared_diff = (x_expanded - y_expanded) ** 2
squared_dist = np.sum(squared_diff, axis=2)
dist = np.sqrt(squared_dist)


dist


array([[1.72800611, 2.3101138 , 0.69672936],
       [2.284949  , 2.697942  , 2.33769291]])

In [31]:
# x_sq = np.sum(x**2, axis=1)
# y_sq = np.sum(y**2, axis=1)
# display(x_sq)
# display(y_sq)

array([0.28410431, 3.84828813])

array([2.04811745, 5.16371739])

In [35]:
data = np.array([
            [1.,    2.,     3.,     1],
            [1.,    np.nan, 3.,     1],
            [7.,    np.nan, 9.,     0],
            [7.,    8.,     9.,     0],
            [26.,   27.,    28.,    np.nan],
            [2.,    3.,     4.,     np.nan],
            [16.,   17.,    18.,    1],
            [np.nan,17.,    18.,    1],
            [11.,   12.,    13.,    np.nan],
            [22.,   23.,    24.,    0],
            [np.nan,23.,    24.,    0],
            [19.,   20.,    21.,    np.nan]
        ])


In [68]:
# labeled_incomplete: n x (D+1) array (n <= N) where values contain incomplete features but complete labels

'''
    data set for incomplete  = data[:, :-1] excludes the last col, takes all rows --> featueres no label 
'''
incomp_features=  data[np.any(np.isnan(data[:, :-1]), axis=1)]
'''
    data set for complete lavel = data[:, -1] all the rows but the last col 
'''
#comp_labels = data[~np.isnan(data[:, -1])]
y_data = incomp_features[:,-1]


display(incomp_features)
data[:, :-1]
data[:, -1]
y_data


array([[ 1., nan,  3.,  1.],
       [ 7., nan,  9.,  0.],
       [nan, 17., 18.,  1.],
       [nan, 23., 24.,  0.]])

array([1., 0., 1., 0.])

In [69]:
data = np.array([
            [1.,    2.,     3.,     1],
            [1.,    np.nan, 3.,     1],
            [7.,    np.nan, 9.,     0],
            [7.,    8.,     9.,     0],
            [26.,   27.,    28.,    np.nan],
            [2.,    3.,     4.,     np.nan],
            [16.,   17.,    18.,    1],
            [np.nan,17.,    18.,    1],
            [11.,   12.,    13.,    np.nan],
            [22.,   23.,    24.,    0],
            [np.nan,23.,    24.,    0],
            [19.,   20.,    21.,    np.nan]
        ])


In [75]:

"""
    Args:
        data: N x (D+1) numpy array where the last column is the labels   
    Return:
        unlabeled_complete: n x (D+1) array (n <= N) where values contain complete features but incomplete labels
"""
y = data[:, -1]
incomp_y = data[np.isnan(y)]

y
incomp_y


array([[26., 27., 28., nan],
       [ 2.,  3.,  4., nan],
       [11., 12., 13., nan],
       [19., 20., 21., nan]])

In [76]:
complete_data = np.array([[1.,2.,3.,1],[7.,8.,9.,0],[16.,17.,18.,1],[22.,23.,24.,0]])
incomplete_data = np.array([[1.,np.nan,3.,1],[7.,np.nan,9.,0],[np.nan,17.,18.,1],[np.nan,23.,24.,0]])
correct_clean_data = np.array([
            [ 1.   ,2.   ,3.   ,1. ],
            [ 7.   ,8.   ,9.   ,0. ],
            [16.  ,17.  ,18.   ,1. ],
            [22.  ,23.  ,24.   ,0. ],
            [14.5 ,23.  ,24.   ,0. ],
            [ 7.  ,15.5  ,9.   ,0. ],
            [ 8.5 ,17.  ,18.   ,1. ],
            [ 1.   ,9.5  ,3.   ,1. ]])

In [4]:
import numpy as np 
import numpy.random as random 

In [10]:
N = np.random.randn(5, 4)
N = N.shape[0]
display(N)

exp_N = np.exp(N)
display(exp_N)

sum_ep = np.sum(exp_N, axis=1, keepdims=True)

prob = np.divide(exp_N, sum_ep)

print(prob)

5

148.4131591025766

AxisError: axis 1 is out of bounds for array of dimension 0

In [11]:
logit = np.array([[1.0, 2.0], [3.0, 4.0]])

exp_form = np.exp(logit) #exp of all i in logit
sum_exp = np.sum(exp_form, axis=1, keepdims=True) #sum of all the exp 
prob = np.divide(exp_form, sum_exp)

display(prob)


array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])

In [12]:
low_dim_logit = logit - np.max(logit, axis=1, keepdims=True)
exp_form = np.exp(low_dim_logit) #exp of all i in logit
sum_exp = np.sum(exp_form, axis=1, keepdims=True) #sum of all the exp 
prob = np.divide(exp_form, sum_exp)


display(prob)

array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])